### ISSUE TITLE
Request for a feature

### ISSUE THREAD

**Issue by sec000** [dwisiswant0/cf-check#1]
Hey, is that possible to fetch the fresh Cloudflare IP's and then work on that.I am doing the same thing in bash but i think go will work fast when there are large dataset of IP's
```
curl http://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips | jq | grep -oE "\"[0-9].*\"" | cut -d"\"" -f2 >> ranges.txt
grepcidr -v -f ranges.txt ip.txt | sort -u > validip.txt
rm ranges.txt
```

**Comment by Bedrovelsen** [comment]
> Hey, is that possible to fetch the fresh Cloudflare IP's and then work on that.I am doing the same thing in bash but i think go will work fast when there are large dataset of IP's
> 
> ```
> 
> curl http://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips | jq | grep -oE "\"[0-9].*\"" | cut -d"\"" -f2 >> ranges.txt
> 
> grepcidr -v -f ranges.txt ip.txt | sort -u > validip.txt
> 
> rm ranges.txt
> 
> ```

Cloudfront is not cloudflare. 

May want to point your curls to the data sets on crimeflare.org 

http://www.crimeflare.org:82/cfusers.html

Or

http://www.crimeflare.org:82/cfnsdump.html

Or fetch the lists for local usage 

http://www.crimeflare.org:82/zippy.html
