### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by Drjacky** [dwisiswant0/cf-check#28]
Do you have plan to support macOS as well?
When I run it, I get:
`zsh: exec format error: cf-check`

**Comment by dwisiswant0** [comment]
It’s already cross-platform compatible. How did you install the tool?

**Comment by Drjacky** [comment]
`go install github.com/dwisiswant0/cf-check@latest`.

I had it when I had an Intel Mac. Then I migrated to a Silicon Mac and everything came to the new machine. So right now, I have it in `/usr/local/bin/cf-check`. and I do not have it in `/opt/homebrew` even when I install it again.

The output of `file cf-check`:
```
/usr/local/bin/cf-check: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=YgbnFSd6uJSZuSmL7YF2/0P0U4Wt6roRdOLngR3yN/V9qvCGcScNAT3X5wTdmM/jmpNoEFzbvpFfMFJsEbh, not stripped
```

**Comment by Drjacky** [comment]
I had to delete the x86 version, then copy-paste the one with arm64 from `/Users/usernameeee/go/bin/cf-check` into `/usr/local/bin/HERE`
