### ISSUE TITLE
Throwing some error while using on raspi(aarch64)

### ISSUE THREAD

**Issue by 0-0eth0** [dwisiswant0/cf-check#3]
Hi team,
I have tried installing this tool every way, but at last its throwing me an error while running.i am on the latest version of this tool. i am running this tool on my raspi(aarch64) tried building the project in raspi too but didn't worked.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x79 pc=0x83808]

goroutine 1 [running]:
bufio.(*Scanner).Scan(0x0, 0x140b78)
        /snap/go/7018/src/bufio/scan.go:136 +0x28
main.main()
        /root/mytools/tools/cf-check-1.0.2/main.go:63 +0x320
```

Thanks in advance!

**Comment by 0-0eth0** [comment]
@dwisiswant0 i am sorry to disturb you, please look into this whenever you get free.

**Comment by dwisiswant0** [comment]
Are you already using `arm64` version _(pre-built binary)_, @0-0eth0?

**Comment by 0-0eth0** [comment]
Solved! I missed a release page, apologies!!
