### ISSUE TITLE
[Suggestion] Check for Cloudflare Proxy on a Website

### ISSUE THREAD

**Issue by MC874** [dwisiswant0/cf-check#8]
# Description
Some website doesn't use cloudflare IP but it's uses Cloudflare Proxy. The target: Add an ability to make url (that has Cloudflare Proxy) part of `-cf` or `cloudflare` group. 

# Example
URL : bt21club.com
IP : 23.227.38.32

It has Cloudflare Proxy turned on and can be used as normal Remote Proxy.

**Comment by dwisiswant0** [comment]
Hi @MC874, thanks for your feedback!
I believe that this should be fixed properly, please upgrade to the last version.
